### ISSUE TITLE
Cannot access private resources on my local server (v5.0.0-beta.0)

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#994]
I've set up a local server using the self-signed certificates, created a local WebID, and logged in with the newly created WebID. But my user is not recognized by the server, and I'm not allowed to access private resources.

![image](https://user-images.githubusercontent.com/775139/49343636-4f601380-f63b-11e8-9dba-b7b943ae50c7.png)

(I've modified auth-buttons to log the session object.)

It seems that cookies are not set, so that might a clue to why it is not working properly.

The full log from my local server when trying to access my private container.

```
  solid:index Looking for index in /private/ +45s
  solid:ACL Using ACL https://megoth.localhost:8443/private/.acl for ./ +7ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/private/> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/private/> by null and origin null +0ms
  solid:ACL    1 direct authentications about <https://megoth.localhost:8443/private/> +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/private/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +1ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Read> Denying with User Unauthorized +0ms
  solid:ACL Read access denied to (none): 401 - User Unauthorized +0ms
  solid:server Error page because of: { [HTTPError: User Unauthorized] name: 'HTTPError', message: 'User Unauthorized', status: 401 } +0ms
  solid:server Display login-required for https://megoth.localhost:8443/private/ +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +1s
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +3ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +1ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +1ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +1ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +0ms
  solid:ACL Using ACL https://megoth.localhost:8443/favicon.ico.acl for ./favicon.ico +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +1ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +1ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Write> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +1ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Append> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +1ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Control> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +1ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +1ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Write> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +1ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +1ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Append> Denying with User Unauthorized +1ms
  solid:ACL accessDenied: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL modesAllowed: checking access to <https://megoth.localhost:8443/favicon.ico> by null and origin null +0ms
  solid:ACL    2 direct authentications about <https://megoth.localhost:8443/favicon.ico> +1ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +1ms
  solid:ACL      The agent/group/public check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL    Checking auth <https://megoth.localhost:8443/favicon.ico.acl#public> with agent null +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Control> Denying with User Unauthorized +1ms
  solid:ACL Permissions on https://megoth.localhost:8443/favicon.ico for (none): read +0ms
  solid:ACL Permissions on https://megoth.localhost:8443/favicon.ico for public: read +0ms
  solid:get /favicon.ico on megoth.localhost +0ms
  solid:handlers GET -- Reading /Users/megoth/Projects/solid/node-solid-server/data/megoth.localhost/favicon.ico +2ms
```

**Comment by rubensworks** [comment]
This may be related, but I can not PUT private files anymore either:

> Error: Web error: 403 (Forbidden) on PUT of <https://locall.localhost:8443/private/test.ttl>

**Comment by rubensworks** [comment]
The PUT bug seems to be caused by something else though, as the ACL checker returns an "Origin Unauthorized" message.

**Comment by kjetilk** [comment]
Ooops, that is interesting... Do we see the same thing on dev.inrupt.net?

**Comment by kjetilk** [comment]
Uh-oh! Great if you can look into this, since I'm not getting to it.

**Comment by rubensworks** [comment]
Fixed in https://github.com/solid/acl-check/pull/13, but not sure if the proposed fix is spec-compliant. So it would be good if someone with more knowledge on .acl files could double-check that.

**Comment by megoth** [comment]
Sorry for late response.

I'm still unable to be recognized by the server when I'm logged in with the local server =/ I'll debug it more to understand what is going on.

**Comment by megoth** [comment]
Hmm, seems that things are working now. I'm at least not able to reproduce this bug anymore ^_^

I'm closing this issue.

**Comment by CxRes** [comment]
This still seems to be an issue with v5.0.0 server. I am unable to login on my local setup (running on node v8.15 on Windows 10 64-bit). This has also been reported on the solid forum [here](https://forum.solidproject.org/t/local-setup-solid-server-gets-bugs/995).

**Comment by michielbdejong** [comment]
@CxRes thanks for reporting! I'll see if I can replicate it with latest master.

**Comment by jaxoncreed** [comment]
As of right now, I cannot replicate this. However, I do remember accidentally running into this issue earlier. Here's hoping I'll run into it again, and I'll attempt to fix it at that point.

**Comment by CxRes** [comment]
@jaxoncreed Could you walk me through your local setup please (to see if I am doing something different that precipitates this). Also since I am running into this issue, is there some place I can look (I am afraid that I am new to this project and unfamiliar with the codebase).

**Comment by jaxoncreed** [comment]
Haha. Feel free to do some code spelunking, but at the moment, it's not the easiest thing to do.

Here's my config if that's interesting to you:

```
{
  "root": "/Users/m/inrupt/node-solid-server/data",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "../privkey.pem",
  "sslCert": "../fullchain.pem",
  "multiuser": false,
  "server": {
    "name": "localhost",
    "description": "",
    "logo": ""
  }
}
```

Maybe there are a few things that can help be debug this:
 - Tell me if you're running a multi-user pod or a single user pod?
 -  Send me the .acl file of the resource you're trying to request (you can find this in your data folder)

**Comment by CxRes** [comment]
@jaxoncreed My config looks identical to yours with the exception that absolute paths are used for `sslKey` and `sslCert`.

I am running single user mode

My `.acl` looks like this:
```
# Root ACL resource for the user account
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

# The homepage is readable by the public
<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo </>;
    acl:mode acl:Read.

# The owner has full access to every resource in their pod.
# Other agents have no access rights,
# unless specifically authorized in other .acl resources.
<#owner>
    a acl:Authorization;
    acl:agent <https://localhost:8443/profile/card#me>;
    # Optional owner email, to be used for account recovery:
    acl:agent <mailto:aaa@bbb.com>;
    # Set the access to the root storage folder itself
    acl:accessTo </>;
    # All resources will inherit this authorization, by default
    acl:default </>;
    # The owner has all of the access modes allowed
    acl:mode
        acl:Read, acl:Write, acl:Control.
```

When I try to log in from the browser, I get the following error on my devtools console:
```
Error: Error registering client: 500 Internal Server Error
    at popup.html:24
    at async https:/localhost:8443/common/popup.html:24
    at async Xe (popup.html:24)
    at async Object.<anonymous> (popup.html:24)
```

popup.html (`solid-auth-client/dist-popup/popup.html`) contains bundled js with no sourcemaps, I think I have hit a dead end. It a very strange thing to do!!!!????

**Comment by jaxoncreed** [comment]
Oh, I just remembered that I created an issue for something that might be the same thing a few days ago #1155.

To test if this is the same thing, open up your development tools and go to "local storage" and delete the key that's present. Then try logging in again. If you don't want to do that, you can see if logging in in incognito mode works for you.

**Comment by CxRes** [comment]
Does not help. When I click **Localhost:8443** on the login, I get the following errors:
```
popup.html: 24 Error logging in with WebID-OIDC
Xe @ popup.html:24
async function (async)
Xe @ popup.html:24
login @ popup.html:24
(anonymous) @ popup.html:24
async function (async)
(anonymous) @ popup.html:24
E @ popup.html:24
popup.html:24 

Error: Error registering client: 500 Internal Server Error
    at popup.html:24
Xe @ popup.html:24
async function (async)
Xe @ popup.html:24
login @ popup.html:24
(anonymous) @ popup.html:24
async function (async)
(anonymous) @ popup.html:24
E @ popup.html:24
popup.html:24 

POST https://localhost:8443/register 500 (Internal Server Error)
register @ popup.html:24
(anonymous) @ popup.html:24
Promise.then (async)
register @ popup.html:24
(anonymous) @ popup.html:24
(anonymous) @ popup.html:24
async function (async)
(anonymous) @ popup.html:24
Xe @ popup.html:24
login @ popup.html:24
(anonymous) @ popup.html:24
async function (async)
(anonymous) @ popup.html:24
E @ popup.html:24
```

**Comment by jaxoncreed** [comment]
@CxRes I've just been able to reproduce this issue, so I'll get to work on it and hopefully will have something by end of day.

**Comment by jaxoncreed** [comment]
@rimmartin Here's the situation. The problem is caused by session cookies not being set. Each web browser handles cookies on localhost a bit differently. For example, Chrome does not set cookies for subdomains of localhost. Because subdomains are required for multiuser, the data browser will not work in chrome on localhost. I have not found another web browser where it does work. So, you have two options:

1. Do all your development in "multiuser: false" mode
2. Stand up a remote server to run your pod

Does this sound like it addresses your issue?

**Comment by michielbdejong** [comment]
Would it help if instead of https://user1.localhost you try it with https://user1.lolcathost.de (which also points to 127.0.0.1)?

**Comment by jaxoncreed** [comment]
Closing this out because of inactivity
